import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import type { Host } from "./detect.js";
import { applyInjectionBlock, removeInjectionBlock } from "./injection.js";

// Usage guidance tk drops at `tk install` so the agent SPENDS FEWER TOKENS — not
// just the transparent `tk <cmd>` rewrite the hook/shim already does, but the
// agent-actionable habits the research (docs/reports/token-optimization-best-practices)
// found move the needle most: prefer a tool's native terse form, read/search with
// the agent's own bounded tools instead of shelling out (orientation is where most
// tokens leak), and keep the agent's own replies short (output is billed ~4× input).
// This file is AGENT-facing — every line is a habit the model can act on. Human-only
// surfaces (the `tk gain`/`tk inspect` analytics) are NOT here; they belong on the
// CLI, not in always-on resident context. Written as a dedicated, tk-owned `TK.md`
// so it never tangles with the user's own CLAUDE.md content.

const GUIDANCE_FILENAME = "TK.md";

// VS Code Copilot auto-loads a user-level `.instructions.md` from the user
// profile (`~/.copilot/instructions`) across all workspaces (verified against the
// VS Code custom-instructions docs, ADR 0008). Unlike claude-code (which pulls
// TK.md in via an `@import` VS Code does NOT expand) the file IS the loaded
// instruction, so tk writes the full guide inlined, under an `applyTo: '**'`
// always-on frontmatter.
const VSCODE_GUIDANCE_FILENAME = "token-killer.instructions.md";

// Self-contained guidance doc. The whole file is tk's — overwritten on re-init,
// deleted on uninstall — so it needs no inline markers.
export function guidanceDoc(): string {
  return `${[
    "# Token Killer — usage guide",
    "",
    "_Generated by `tk install`. tk runs the real tool and compresses its output so",
    "you spend far fewer tokens. Being token-efficient is your job too: route output-",
    "heavy commands through tk, ask tools for their terse forms, and keep replies short._",
    "",
    "## Route output-heavy commands through tk",
    "",
    "Prefix shell commands with `tk` — it runs the real tool and compresses the output",
    "before it reaches you (typically 60–90% on common dev commands, transparently). The",
    "more you route through tk, the fewer tokens you burn reading tool output.",
    "",
    "- Reading files: **`tk read --max-lines 200 <file>`** (or `--level aggressive` for a",
    "  symbol outline) — don't `cat` a whole large file.",
    "- Searching: **`tk rg <pattern> <path>`** scoped to a dir — tk caps results",
    "  automatically; `--level minimal` keeps every match (deduped, lossless), `--raw` verbatim.",
    "- Directory trees: **`tk tree <path>`** — auto-caps oversized dirs; `-L <n>` to go shallower.",
    "- Anything else high-output (build/test/log/`docker`/`kubectl`/`gh` …): just prefix `tk`.",
    "",
    "## Prefer native terse forms",
    "",
    "When a tool has an already-minimal mode, ask for it — smallest and most reliable",
    "(tk passes these through unchanged):",
    "",
    '- `git status` → **`git status --short`** (drops the `(use "git …")` hints + headers)',
    "- `git log` → **`git log --oneline`** (one line/commit; bound it with `-<n>`)",
    "- `git diff` → **`git diff --stat`** for file/line counts; full diff only to read hunks",
    "- `git show` → **`git show --stat`** for the summary; full only to read changes",
    "- `grep`/`rg` → **`-c`/`-l`/`-o`** when you only need counts/filenames/matches, not full lines",
    "",
    "## Keep your own replies short",
    "",
    "Output tokens are billed ~4× input, so your own verbosity is the most expensive",
    "thing in the loop. Answer with code and the minimum explanation the task needs;",
    "skip preamble, restatement, and recaps. Don't re-read a file or repeat a search",
    "whose result is already in context.",
  ].join("\n")}\n`;
}

// Dedicated guidance file per host — written ONLY for hosts that actually read a
// standalone file: claude-code pulls ~/.claude/TK.md in via `@import`; vscode's
// `.instructions.md` IS the auto-loaded file. copilot-cli has NO standalone file
// (I4): it has no import syntax, so the guidance is inlined into its loader
// (copilot-instructions.md, see guidanceLoader) and a separate ~/.copilot/TK.md was
// dead weight the host never loaded. Other hosts have no stable home for it.
export function guidanceFilePath(host: Host, home = homedir()): string | undefined {
  if (host === "claude-code") return join(home, ".claude", GUIDANCE_FILENAME);
  if (host === "vscode") return join(home, ".copilot", "instructions", VSCODE_GUIDANCE_FILENAME);
  return undefined;
}

// The exact bytes written to a host's standalone guidance file. claude-code gets
// the bare doc (it pulls it in via `@import`). vscode's file is the auto-loaded
// instruction itself, so it carries the `applyTo: '**'` always-on frontmatter the
// `.instructions.md` format requires and inlines the full doc (no `@import`
// indirection — VS Code does not resolve it). copilot-cli has no standalone file
// (its guidance is inlined into the loader, see guidanceLoader), so this is never
// called for it.
export function guidanceFileContent(host: Host): string {
  if (host === "vscode") return `---\napplyTo: '**'\n---\n\n${guidanceDoc()}`;
  return guidanceDoc();
}

// The auto-loaded instructions file that must reference the guidance so the agent
// actually reads it, plus the body to inject under tk's guarded markers:
//   - claude-code reads ~/.claude/CLAUDE.md and supports `@file` imports → a one
//     line `@TK.md` pulls the dedicated file in.
//   - copilot-cli reads ~/.copilot/copilot-instructions.md but has NO import
//     syntax → inline the full guidance so it is actually loaded.
export function guidanceLoader(
  host: Host,
  home = homedir(),
): { path: string; body: string } | undefined {
  if (host === "claude-code") {
    return {
      path: join(home, ".claude", "CLAUDE.md"),
      body: ["## Token Killer", "", `@${GUIDANCE_FILENAME}`].join("\n"),
    };
  }
  if (host === "copilot-cli") {
    return {
      path: join(home, ".copilot", "copilot-instructions.md"),
      body: guidanceDoc().trimEnd(),
    };
  }
  return undefined;
}

// Write the dedicated guidance file (whole file is ours) and wire the loader line
// into the host's auto-loaded instructions (marker-guarded, idempotent). Returns
// the paths touched so the caller can report them.
export function writeGuidance(
  host: Host,
  home = homedir(),
): { guidance?: string; loader?: string } {
  const result: { guidance?: string; loader?: string } = {};

  const guidancePath = guidanceFilePath(host, home);
  if (guidancePath) {
    mkdirSync(dirname(guidancePath), { recursive: true });
    writeFileSync(guidancePath, guidanceFileContent(host));
    result.guidance = guidancePath;
  }

  const loader = guidanceLoader(host, home);
  if (loader) {
    mkdirSync(dirname(loader.path), { recursive: true });
    const existing = existsSync(loader.path) ? readFileSync(loader.path, "utf8") : "";
    writeFileSync(loader.path, applyInjectionBlock(existing, loader.body));
    result.loader = loader.path;
  }

  return result;
}

// Reverse of writeGuidance: delete the dedicated file, strip the loader block.
export function unwriteGuidance(host: Host, home = homedir()): void {
  const guidancePath = guidanceFilePath(host, home);
  if (guidancePath && existsSync(guidancePath)) rmSync(guidancePath, { force: true });

  const loader = guidanceLoader(host, home);
  if (loader && existsSync(loader.path)) {
    writeFileSync(loader.path, removeInjectionBlock(readFileSync(loader.path, "utf8")));
  }
}
