import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

import type { Host } from "./detect.js";
import { applyInjectionBlock, removeInjectionBlock } from "./injection.js";

// Usage guidance tk drops at `tk init` so the agent uses tk WELL — not just the
// `tk <cmd>` prefix the injection block teaches, but the habits that actually
// move the needle: prefer a tool's native terse form (the proxy passes those
// through, and they stay small even when it can't help), and read `gain`'s
// 0%-row labels honestly. Written as a dedicated, tk-owned `TK.md` so it never
// tangles with the user's own CLAUDE.md content.

const GUIDANCE_FILENAME = "TK.md";

// Self-contained guidance doc. The whole file is tk's — overwritten on re-init,
// deleted on uninstall — so it needs no inline markers.
export function guidanceDoc(): string {
  return `${[
    "# Token Killer — usage guide",
    "",
    "_Generated by `tk init`. tk wraps a dev command, runs the real tool, and",
    "compresses its output so coding agents spend far fewer tokens._",
    "",
    "## Prefer native terse forms",
    "",
    "You save the most — and most reliably — by asking the tool for its already-",
    "minimal output. tk passes those through unchanged (a 0% in `gain` here is",
    "healthy), and they stay small even when tk can't help (piped commands, or",
    "programs with no handler, run raw).",
    "",
    '- `git status` → **`git status --short`** (drops the `(use "git …")` hints + headers)',
    "- `git log` → **`git log --oneline`** (one line/commit; bound it with `-<n>`)",
    "- `git diff` → **`git diff --stat`** when you only need file/line counts; full diff only to read hunks",
    "- `git show` → `git show --stat` for the summary; full only to read changes",
    "- `grep`/`rg` → `-c`/`-l`/`-o` when you only need counts/filenames/matches, not full lines",
    "- Reading files → prefer the Read tool or `head`/`tail`/`sed -n` over `cat` on",
    "  large files: prose/source can't be losslessly compressed, so a full `cat` is paid in full",
    "",
    "## Read `gain` honestly",
    "",
    "`tk gain` shows measured savings; `tk gain --history` lists recent commands.",
    "A 0%-savings row is HEALTHY when the input was already minimal or is prose tk",
    "won't truncate — only an unexpectedly large uncompressed output is worth a look.",
    "",
    "## Meta commands (run `tk` directly)",
    "",
    "```bash",
    "tk gain              # measured token savings",
    "tk gain --history    # recent commands + per-command savings",
    "tk inspect           # scan agent history for missed savings",
    "tk --raw <cmd>       # run a command WITHOUT compression (debugging)",
    "```",
  ].join("\n")}\n`;
}

// Dedicated guidance file per host. claude-code → ~/.claude/TK.md;
// copilot-cli → ~/.copilot/TK.md. Other hosts have no stable home for it.
export function guidanceFilePath(host: Host, home = homedir()): string | undefined {
  if (host === "claude-code") return join(home, ".claude", GUIDANCE_FILENAME);
  if (host === "copilot-cli") return join(home, ".copilot", GUIDANCE_FILENAME);
  return undefined;
}

// The auto-loaded instructions file that must reference the guidance so the agent
// actually reads it, plus the body to inject under tk's guarded markers:
//   - claude-code reads ~/.claude/CLAUDE.md and supports `@file` imports → a one
//     line `@TK.md` pulls the dedicated file in.
//   - copilot-cli reads ~/.copilot/copilot-instructions.md but has NO import
//     syntax → inline the full guidance so it is actually loaded.
export function guidanceLoader(
  host: Host,
  home = homedir(),
): { path: string; body: string } | undefined {
  if (host === "claude-code") {
    return {
      path: join(home, ".claude", "CLAUDE.md"),
      body: ["## Token Killer", "", `@${GUIDANCE_FILENAME}`].join("\n"),
    };
  }
  if (host === "copilot-cli") {
    return {
      path: join(home, ".copilot", "copilot-instructions.md"),
      body: guidanceDoc().trimEnd(),
    };
  }
  return undefined;
}

// Write the dedicated guidance file (whole file is ours) and wire the loader line
// into the host's auto-loaded instructions (marker-guarded, idempotent). Returns
// the paths touched so the caller can report them.
export function writeGuidance(
  host: Host,
  home = homedir(),
): { guidance?: string; loader?: string } {
  const result: { guidance?: string; loader?: string } = {};

  const guidancePath = guidanceFilePath(host, home);
  if (guidancePath) {
    mkdirSync(dirname(guidancePath), { recursive: true });
    writeFileSync(guidancePath, guidanceDoc());
    result.guidance = guidancePath;
  }

  const loader = guidanceLoader(host, home);
  if (loader) {
    mkdirSync(dirname(loader.path), { recursive: true });
    const existing = existsSync(loader.path) ? readFileSync(loader.path, "utf8") : "";
    writeFileSync(loader.path, applyInjectionBlock(existing, loader.body));
    result.loader = loader.path;
  }

  return result;
}

// Reverse of writeGuidance: delete the dedicated file, strip the loader block.
export function unwriteGuidance(host: Host, home = homedir()): void {
  const guidancePath = guidanceFilePath(host, home);
  if (guidancePath && existsSync(guidancePath)) rmSync(guidancePath, { force: true });

  const loader = guidanceLoader(host, home);
  if (loader && existsSync(loader.path)) {
    writeFileSync(loader.path, removeInjectionBlock(readFileSync(loader.path, "utf8")));
  }
}
